version: '3'

services:

  couchdb:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/mrs-events-db
    volumes:
      - /opt/data/mrs-events:/opt/couchdb/data
    labels:
      - "docker-backup.name=mrs-events"
      - "docker-backup.max-age=43200000"
      - "docker-backup.command=/opt/scripts/couchdb-backup-wrapper.sh"
      - "docker-backup.file=/opt/backups/mrs-events.json"
    networks:
      monitoring-network:
        aliases:
          - mrs-events-db

networks:
  monitoring-network:
    external: true
