version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/mrs-server
    networks:
      monitoring-network:
        aliases:
          - mrs-server

networks:
  monitoring-network:
    external: true
