version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/mrs-web
    networks:
      monitoring-network:
        aliases:
          - mrs-web

networks:
  monitoring-network:
    external: true
