version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/mrs-proxy
    ports:
      - 80:80
    networks:
      monitoring-network:
        aliases:
          - mrs-proxy

networks:
  monitoring-network:
    external: true
